name = "gleamsver"
version = "1.0.1"

description = "Comprehensive set of native Gleam utilities for handling SemVer 2.0.0 version strings."
licences = ["MIT"]
repository = { type = "github", user = "aznashwan", repo = "gleamsver" }
links = [{ title = "GitHub", href = "https://github.com/aznashwan/gleamsver" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
